import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

// The registry is auto-generated by scripts/gen-registry.mjs. This test
// fails if anyone hand-edits src/tools/registry.ts (or adds a tool file
// and forgets to regenerate) — running `npm run gen:registry` fixes it.
//
// The npm hooks (prebuild/pretest/predev/prelint/pretypecheck) run the
// generator automatically, so the only way this test fails in CI is if
// someone deliberately edited the file. Treat the assertion failure as
// "you broke the contract: tool files are the source of truth, registry
// is generated."

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

describe("registry: auto-generation stays in sync with src/tools", () => {
  it("regenerating produces no diff against the checked-in registry.ts", () => {
    const before = readFileSync(join(ROOT, "src/tools/registry.ts"), "utf8");
    execFileSync("node", ["scripts/gen-registry.mjs"], {
      cwd: ROOT,
      stdio: "ignore",
    });
    const after = readFileSync(join(ROOT, "src/tools/registry.ts"), "utf8");
    expect(
      after,
      "registry.ts is out of sync with src/tools/. Run `npm run gen:registry`.",
    ).toBe(before);
  });
});
