// AUTO-GENERATED by scripts/gen-registry.mjs — DO NOT EDIT BY HAND.
// To add a tool: drop a new file in src/tools/<name>.ts exporting either
// `<camel>Tool` (regular) or `build<Camel>Tool(otherTools)` (factory),
// then run `npm run gen:registry` (or any of prebuild/pretest/predev,
// which re-run it for you).
import { colorTool } from "./color.js";
import { convertDataTool } from "./convert-data.js";
import { diffTool } from "./diff.js";
import { dnsTool } from "./dns.js";
import { encodeTool } from "./encode.js";
import { hashTool } from "./hash.js";
import { httpTool } from "./http.js";
import { idTool } from "./id.js";
import { inspectTool } from "./inspect.js";
import { jsonQueryTool } from "./json-query.js";
import { jwtTool } from "./jwt.js";
import { netTool } from "./net.js";
import { numberTool } from "./number.js";
import { regexTool } from "./regex.js";
import { buildScriptTool } from "./script.js";
import { textTool } from "./text.js";
import { timeTool } from "./time.js";
import type { ToolDef } from "./types.js";

// biome-ignore lint/suspicious/noExplicitAny: heterogeneous tool shapes
const everythingElse: ToolDef<any>[] = [
  colorTool,
  convertDataTool,
  diffTool,
  dnsTool,
  encodeTool,
  hashTool,
  httpTool,
  idTool,
  inspectTool,
  jsonQueryTool,
  jwtTool,
  netTool,
  numberTool,
  regexTool,
  textTool,
  timeTool,
];

// Factory tools are appended last so they can dispatch into every other
// tool while being unable to invoke themselves (no recursion).
// biome-ignore lint/suspicious/noExplicitAny: heterogeneous tool shapes
export const tools: ToolDef<any>[] = [
  ...everythingElse,
  buildScriptTool(everythingElse),
];
